### ISSUE TITLE
Demo error on Windows

### ISSUE THREAD

**Issue by TheEditor** [evidence-dev/evidence#127] opened 2021-09-06 03:42 UTC
Windows 10, error running demo, URL is localhost:3000:

`500
Unexpected token 'export'
C:\Users\davef\OneDrive\Documents\home\evidence-dev\my-project\node_modules\layercake\src\index.js:1
export { default as LayerCake } from './LayerCake.svelte';
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at nodeRequire (C:\Users\davef\OneDrive\Documents\home\evidence-dev\my-project\node_modules\@sveltejs\kit\node_modules\vite\dist\node\chunks\dep-1be34a63.js:75033:17)
    at ssrImport (C:\Users\davef\OneDrive\Documents\home\evidence-dev\my-project\node_modules\@sveltejs\kit\node_modules\vite\dist\node\chunks\dep-1be34a63.js:74975:20)`

**Comment by hughess** [comment] 2021-09-06 15:02
Hi @TheEditor, sorry you ran into this issue! This is a problem with our Windows support - one of the packages we use isn't able to read some of our JS files on Windows. This is a high priority issue for us, so hopefully we will have an update on it this week.

While I'm still not 100% sure the cause of this issue, I believe it's related to #121.

Closing this as we have an issue for Windows support open already (#15).

**Closed by hughess** 2021-09-06 15:02 UTC
Labels: duplicate
