### ISSUE TITLE
Support deploying to a subpath 

### ISSUE THREAD

**Issue by davidgasquez** [evidence-dev/evidence#1527] opened 2024-01-26 11:10 UTC
## Steps To Reproduce

I started deploying Evidence on my project site, doing some manual copying to put the Evidence `build` output into a subpath (`/reports`). 

When loading the deployed Evidence reports (/reports), I'm getting 404s as Evidence looks for all those files in `domain.com/_app/immutable/` instead of `domain.com/reports/_app/immutable/`.

### Extra Context

- [Steps I'm running to deploy](https://github.com/davidgasquez/datadex/blob/main/Makefile#L20-L31)
- [Deployed site with errors](https://davidgasquez.github.io/datadex/reports/)

### Environment

- Node version (`node -v`): v18.19.0
- npm version (`npm -v`): 10.2.3
- OS: Ubuntu 22.04
- Browser: Brave
- Database: DuckDB

**Comment by archiewood** [comment] 2024-01-26 13:19
Hey @davidgasquez great to have you here!


Did you see
https://github.com/evidence-dev/evidence/issues/603

**Comment by davidgasquez** [comment] 2024-01-26 18:17
> Hey @davidgasquez great to have you here!

It took a long time to post any issue so that's a win in terms of DX! :raised_hands:

> Did you see #603

I did not. Wasn't sure how to search for the proper issue. I'll try the workaround tomorrow. If it works, I'll close as duplicate.

**Comment by davidgasquez** [comment] 2024-01-29 11:28
The workarounds didn't work. I think I need to dig into the Svelte internals as some commets suggested. 

Curious how would you do it @archiewood!

**Comment by davidgasquez** [comment] 2024-02-19 09:30
Heya @archiewood! Any updates on this one? Would appreciate some new pointers/directions!

**Comment by archiewood** [comment] 2024-02-19 15:59
Hey @davidgasquez 

This is not currently something we support as a deployment path.

We looked into it a while back but it makes the whole DX pretty hairy. (There is a closed PR in that linked issue where there is a bit more discussion).

If the workarounds other have suggested don't work for you (I haven't tested them), some other paths that _might_ work:
- can you deploy to a subdomain? reports.yourdomain.com
- can you embed the evidence project in your subdirectory using an iframe?

If you can share more context I may be able to suggest other paths

**Comment by davidgasquez** [comment] 2024-02-20 10:25
Makes sense! Thanks a lot for the pointers @archiewood. Appreciate the help :pray: 

Will try these workarounds and report back if I figure out a way to make it work.

**Comment by archiewood** [comment] 2024-02-21 12:20
@srenatus 

I'm going to close this issue as it's a duplicate of #603 and it's confusing to have both open right now!

**Closed** 2024-02-21 12:20 UTC
