### ISSUE TITLE
Tooltip formatting in Composable Charts

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#849] opened 2023-05-04 17:59 UTC
**Bug Description**
The tooltip formatted a field incorrectly when it had two different series formats

<img width="766" alt="image" src="https://user-images.githubusercontent.com/58074498/236289099-34bade7a-24b1-44f0-85df-c9525efe08e0.png">

**Severity**

- [ ] High - I'm not able to use Evidence until this bug is fixed
- [ ] Medium - I'm able to use Evidence, but a feature I need to use is not working
- [x] Low - I'm able to keep using Evidence as normal, but flagging this for the team to fix

**Expected Behavior**
The formatting of the tooltip should obey the format tags applied

**Steps To Reproduce**
````
---
title: Mixed Type Charts
sources:
- orders_by_category: orders_by_category.sql
---

## Composable Charts



<Chart 
    data={orders_by_category.filter(d => d.category === "Sinister Toys")}
    x=month
>
    <Bar y=sales_usd0k/>
    <Line y=num_orders_num0/>
</Chart>

````

**Environment Information**
Operating System (e.g., MacOS, Windows 10): MacOS
Browser: Firefox

**Database:**

- [ ] Postgres
- [ ] BigQuery
- [ ] Snowflake
- [ ] Redshift
- [ ] MySQL
- [ ] SQLite
- [x] DuckDB
- [ ] CSV
- [ ] Other (please specify)

**Comment by hughess** [comment] 2023-05-23 13:48
@archiewood this one's expected based on how it's set up at the moment. Basically, the tooltip formatting is applied based on the formatting of the y-axis, so anything in that tooltip will get that formatting.

There's 2 ways this can be solved:
- Add a secondary y-axis and allow the tooltip to pull formatting from either axis depending on the metric
- Get the tooltips to pull formatting from the specific columns referenced, rather than from the y-axis formatting

I think the second option is probably best, and the first can be treated as a separate feature from that. Would require some thinking though - there's a limitation in echarts that makes it a bit difficult to get the tooltip to access the formatting information. 

The other thing we'll need to think about is how this would interact with formatting props in chart components. E.g., `yFmt=$#,##0`

**Comment by hughess** [comment] 2023-06-27 14:16
Closing this one since it's expected behaviour. We can revisit multi-column formatting when adding the secondary y-axis

**Closed by hughess** 2023-06-27 14:16 UTC
Labels: bug, to-review
