### ISSUE TITLE
Pre Render Columns Error

### ISSUE THREAD

**Issue by Kanishk1802** [evidence-dev/evidence#2437] opened 2024-08-15 16:28 UTC
After building locally, I'm coming across this issue in my terminal. Not sure what the specific error is with my query/code. Believe it may be an issue with the how the error is triggered:

<img width="1032" alt="Screenshot 2024-08-15 at 12 27 49 PM" src="https://github.com/user-attachments/assets/305771f8-8adf-46db-bd4f-a24212c3c227">

**Comment by archiewood** [comment] 2024-08-30 09:28
Duplicate of #2315

**Closed by archiewood** 2024-08-30 09:28 UTC
