### ISSUE TITLE
Multiple y axis support

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#404] opened 2022-09-08 20:13 UTC
Be able to have two y-axes with different scales for different series. 
For example:
<img width="910" alt="image" src="https://user-images.githubusercontent.com/58074498/189216907-e38538fd-185c-455f-9c28-037dfc96b4d1.png">

**Comment by hughess** [comment] 2022-09-21 20:21
Closing as duplicate of #412

**Closed by hughess** 2022-09-21 20:21 UTC
Labels: enhancement
