### ISSUE TITLE
Date handling from BQ

### ISSUE THREAD

**Issue by mikeyoungyoung** [evidence-dev/evidence#61] opened 2021-08-13 14:15 UTC
There seems to be an issue with handling dates returned from BQ.
**Problem query**
`SELECT EXTRACT(DATE FROM <timestampe> ) as Date, <some_metric> FROM <some_table>`
returns a nested json object like 
<img width="563" alt="image" src="https://user-images.githubusercontent.com/2731660/129370527-19c793ed-85e5-48a0-908d-8852965b3ee6.png">
and can't be rendered in a chart since I have to reference values as 
<img width="296" alt="image" src="https://user-images.githubusercontent.com/2731660/129370596-25af6f87-7c91-40bc-a747-3cbeb42bc3ff.png">

**working query**
When I extract only month as:
`SELECT EXTRACT(MONTH FROM <timestampe> ) as Date, <some_metric> FROM <some_table>`
The json object is not nested and the chart renders fine

**Comment by mcrascal** [comment] 2021-08-13 15:11
@mikeyoungyoung -- can you share the contents of the package.json file at the root of your project?

**Comment by mikeyoungyoung** [comment] 2021-08-13 15:18
`{
  "name": "~TODO~",
  "version": "0.0.1",
  "scripts": {
    "dev": "svelte-kit dev",
    "build": "svelte-kit build",
    "preview": "svelte-kit preview"
  },
  "devDependencies": {
    "@sveltejs/adapter-static": "^1.0.0-next.11",
    "@sveltejs/kit": "next",
    "vite-plugin-full-reload": "^0.2.2"
  },
  "type": "module",
  "dependencies": {
    "@evidence-dev/components": "^0.0.10",
    "@evidence-dev/db-connectors": "^0.0.6",
    "@evidence-dev/preprocess": "^0.0.3",
    "@google-cloud/bigquery": "^5.6.0",
    "blueimp-md5": "^2.18.0",
    "d3": "^6.7.0",
    "d3-scale": "~3.3.0",
    "fs-extra": "^9.1.0",
    "layercake": "^4.1.0",
    "svelte": "^3.34.0",
    "vite-plugin-live-reload": "^2.1.0"
  }
}
`

**Comment by hughess** [comment] 2021-08-13 16:11
Hey @mikeyoungyoung, looks like you're on an old version. The date issue is fixed in our most recent release. You can initialize a new project to get the up to date release. Let us know if you run into any issues with it.

**Comment by mikeyoungyoung** [comment] 2021-08-13 16:41
@hughess so, likely a n00b question.... but... I did `npm init @evidence-dev/new` in a new folder and got the same package file and dependency versions. Probably user error, but that shouldn't be the case right? Also, has does one just update a current project?

**Comment by mcrascal** [comment] 2021-08-14 22:17
@mikeyoungyoung not a noob question at all -- I was able to reproduce your issue, and we'll be adding this to the docs. Thank you. 

I believe your local NPM registry is falling back to an earlier, cached, version of the installer. You can force it to use the latest version of the installer (0.1.4) by running the following command: 

`
 npm init @evidence-dev/new@latest my-project
`

re: updates to existing projects 
This is coming soon. In a release or two, the whole dependency tree (as well as a bunch of the default scaffolding files) will be behind a single "evidence" dependency. At that point, you'll be able to install updates using `npm update`. See issue #45 

I am going to close the issue for now, but feel free to re-open if @latest doesn't solve it for you.

**Closed by mcrascal** 2021-08-14 22:17 UTC
