### ISSUE TITLE
Unexpected date/datetime/timestamp behaviour

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence#871] opened 2023-05-09 23:19 UTC
## Bug Description
As reported in Slack, in some cases dates defined in queries are being converted into different dates in javascript as a result of faulty timezone logic.

>```
>select '2023-05-05'::date;
>```
>```
><DataTable data="{test}">
></DataTable>
>```
> The resulting table contains 2023-05-04 and the CSV export has :
> Thu May 04 2023 22:00:00 GMT+0200 (heure d'été d'Europe centrale)

### Challenges in solving date/time issues
- Databases and browsers handle dates differently (Firefox/Safari + Snowflake combos have in particular has caused issues in the past)
- Must make assumption that timezone in database is correct (e.g., if stored in UTC, user wants it converted into local timezone)
- Concept of home vs. local timezone. If traveling in a different timezone, should data show as the actual local timezone or the home timezone of the user?
- Concept of company vs. user timezone. E.g., if company is in France and user is in US, should dates align with the company or the user?

### Previous date-related issues/PRs
- #424 
- #423
- #467
- #388 
- #491

## Severity
- [ ] High - I'm not able to use Evidence until this bug is fixed
- [x] Medium - I'm able to use Evidence, but a feature I need to use is not working
- [ ] Low - I'm able to keep using Evidence as normal, but flagging this for the team to fix

**Comment by hughess** [comment] 2023-05-10 01:57
I haven't been able to reproduce the issue yet - I tried changing my timezone to France and got the following:
```
select '2023-05-05'::date
```

`2023-05-05` in the query viewer data table
`Fri May 05 2023 00:00:00 GMT+0200 (heure d’été d’Europe centrale)` in the CSV export

@remilapeyre a few questions to help narrow it down:
- If you click open the query viewer data table, do you see the same date as you're seeing in the DataTable component?
- In the query viewer data table, are you seeing a data type of `date`?
- What's your setup?
   - Operating system
   - Database
   - Browser

**Comment by mcrascal** [comment] 2023-07-31 18:06
Closing until we have a reproduction

**Closed by mcrascal** 2023-07-31 18:06 UTC
Labels: bug, medium-priority, needs refinement

**Comment by lmeerwood** [comment] 2024-01-19 01:05
I believe I have just run in to this problem myself and I am happy to provide some details. 

Just a basic overview is I am trying to make a filter for "Last X Months". On Firefox this does not work because when I add the filter it converts it to a string representation of the full date. However, the same query running on Edge does not convert it to a string. The below screenshots are the exact same query on Firefox and Edge. I have not changed anything between the two runs.

Firefox:
![image](https://github.com/evidence-dev/evidence/assets/6085575/b9f97c71-0b53-47af-8b0f-00ea706f8242)


Edge:
![image](https://github.com/evidence-dev/evidence/assets/6085575/abdb1d05-a095-4115-bfa3-afccb9f10236)


You can see that in Firefox it converts the date to `Thu Oct 19 2023 10:00:00 GMT+1000 (Australian Eastern Standard Time)` and the comparison fails, but in Edge it keeps it as `2023-10-19` and the filter is successful.

I am happy to provide more information if required, or start a new ticket if this is actually unrelated. Cheers.
