### ISSUE TITLE
Webpage building broken after updating to 23.0.4

### ISSUE THREAD

**Issue by dannypage** [evidence-dev/evidence#1374] opened 2023-12-01 18:42 UTC
## Steps To Reproduce

Upgrade to the new version - https://github.com/Skrimmage/Data-Platform/tree/main/frontend
1. Navigate directly to /sports/f1/races
2. Hard reload page, if necessary (throws error 1)
3. `npm run build` (throws error 2)

### Environment

- Node version (`node -v`): v18.17.1
- npm version (`npm -v`): 9.6.7
- OS: Mac 14.1.1 (23B81)
- Browser: Chrome 
- Database: CSVs

## Expected Behavior

Show page with datatables after hitting back on page. Also build the whole website.

### 1 Viewing `/sports/F1/races/ ` on local via `npm run dev`:
 
```
500:Invalid time value

RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at FuseIndex.getFn (/Users/dpage/Projects/Data-Platform/frontend/node_modules/@evidence-dev/core-components/dist/unsorted/viz/DataTable.svelte:145:23)
    at file:///Users/dpage/Projects/Data-Platform/frontend/node_modules/fuse.js/dist/fuse.mjs:399:53
    at Array.forEach (<anonymous>)
    at FuseIndex._addObject (file:///Users/dpage/Projects/Data-Platform/frontend/node_modules/fuse.js/dist/fuse.mjs:398:15)
    at file:///Users/dpage/Projects/Data-Platform/frontend/node_modules/fuse.js/dist/fuse.mjs:350:14
    at Array.forEach (<anonymous>)
    at FuseIndex.create (file:///Users/dpage/Projects/Data-Platform/frontend/node_modules/fuse.js/dist/fuse.mjs:349:17)
    at createIndex (file:///Users/dpage/Projects/Data-Platform/frontend/node_modules/fuse.js/dist/fuse.mjs:462:11)
    at Fuse.setCollection (file:///Users/dpage/Projects/Data-Platform/frontend/node_modules/fuse.js/dist/fuse.mjs:1529:7)
```

### 2 Build error:

```
node:internal/event_target:1016
  process.nextTick(() => { throw err; });
                           ^
Error: 500 /sports/F1/races/ (linked from /sports/F1/races)
To suppress or handle this error, implement `handleHttpError` in https://kit.svelte.dev/docs/configuration#prerender
    at file:///Users/dpage/Projects/Data-Platform/frontend/node_modules/@sveltejs/kit/src/core/config/options.js:212:13
    at file:///Users/dpage/Projects/Data-Platform/frontend/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:64:25
    at save (file:///Users/dpage/Projects/Data-Platform/frontend/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:403:4)
    at visit (file:///Users/dpage/Projects/Data-Platform/frontend/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:236:3)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:300:10)
    at [kOnMessage] (node:internal/worker:311:37)
    at MessagePort.<anonymous> (node:internal/worker:212:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:741:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)

Node.js v18.17.1
libc++abi: terminating due to uncaught exception of type Napi::Error: 
Build failed

file:///Users/dpage/Projects/Data-Platform/frontend/node_modules/@evidence-dev/evidence/cli.js:152
			throw `Build process exited with code ${code}`;
			^
Build process exited with code null
(Use `node --trace-uncaught ...` to show where the exception was thrown)

```

## Workarounds

Downgraded my version for the time-being.

**Comment by archiewood** [comment] 2023-12-01 19:11
notes on getting the evidence project running

doesn't seem to need dagster as the duckdb is version controlled

```
cd frontend
npm i 
npm run dev
```

**Comment by archiewood** [comment] 2023-12-01 19:27
@csjh this first error is complaining about fuse - could this be #1354

**Comment by archiewood** [comment] 2023-12-01 19:48
Note that removing the datatable appears to solve both the above issues, so I am guessing the issue is in there

**Comment by csjh** [comment] 2023-12-02 00:46
Seems to have something to do with the null values in the results being set to `\N` instead of `null` - not sure why it's still being identified as a date column even though those non-date entries are there though

**Comment by archiewood** [comment] 2023-12-22 17:38
Hi @dannypage let us know if this is still an issue in v24+

**Comment by csjh** [comment] 2024-02-21 23:42
Fixed with >24

**Closed by csjh** 2024-02-21 23:42 UTC
Labels: bug

**Comment by dannypage** [comment] 2024-02-23 03:32
Came back around to this, Upgraded to v27 and USQL, and it's working! Thanks all.
