### ISSUE TITLE
Dates without timezones display incorrectly during formatting

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#356] opened 2022-07-21 16:23 UTC
In timezones outside UTC, passing a date without a timezone will assume UTC, which can lead to unexpected outcomes.

# Steps to reproduce

````
```usage_data
select '2022-06-06' as usage_mmm
```

<Value data={usage_data} column=usage_mmm/>
````

should display Jun, Instead displays May.

# Why

If the date doesn’t have a timezone associated with it, JS date assumes UTC timezone in the backend.

So 2022-06-01 would be 2022-06-01 0:00 UTC

At the time of presenting, JS will look at the timezone on the browser and apply it. 

If you are in EST, 2022-06-01 0:00 UTC becomes 2022-05-31 19:00 EST

The month extracted from that would hence be May.

**Comment by hughess** [comment] 2022-09-14 16:00
@archiewood I'm able to reproduce this:
<img width="689" alt="CleanShot 2022-09-14 at 11 45 51@2x" src="https://user-images.githubusercontent.com/12602440/190201502-4d1872bd-2dfc-4c44-85fd-93ff25421328.png">

There's a couple things going on here:
1. The date in this example is of type `string` (see query viewer table in screenshot) and the `Value` component attempts to format it as a date
2. The `Value` component and `QueryDataTable` treat dates differently

`2.` is covered by #382. The JS date handling you outline here is the issue, and I previously tried to solve it in the `Value` component, but not in some other places. I'll add my notes on that in the separate issue.

`1.` brings up a question:
- Should we format dates that are stored as strings, or display them only as strings?

My first inclination is to leave them as strings so there is always a clear path from `data` --> `type = date` --> formatted as date.

**Comment by archiewood** [comment] 2022-09-14 16:30
That makes sense (I think).

What would happen then if I then aliased the field with a format tag eg mydate_dmy?

**Comment by hughess** [comment] 2022-09-14 16:56
If the underlying data is a string, it would show it as a string (unchanged), regardless of any format tags used. As long as the column is type `date`, the format tag would work as expected.

I had completely forgotten that SQLite dates come in as strings...that complicates things

**Comment by hughess** [comment] 2022-09-14 19:24
Although now that I think about it, that should get caught by our type inference logic. If it should be caught by type inference, then I would say we should keep strings as string-formatted.

**Comment by hughess** [comment] 2022-09-14 19:34
I've just switched my db from BigQuery to SQLite and confirmed that it's getting picked up by the type inference logic, so no problems there. Sorry, I'd forgotten we have to handle the types differently between SQLite and other SQL dbs.

Based on the type inference working as expected, I think it makes sense to change the `Value` component to ignore format tags when type is `string`.

**Comment by hughess** [comment] 2022-09-21 20:20
Closing this because the solution will be the same as #382

**Closed by hughess** 2022-09-21 20:20 UTC
Labels: bug, high-priority
