### ISSUE TITLE
[Bug]: Source Plugins are looking for code in the wrong directory

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#2829] opened 2024-11-21 14:48 UTC
### Describe the bug

When attempting to use the clickhouse plugin, (but probably affects all source plugins) Evidence is looking in the wrong directory.

The required package.json  is in is in

`./node_modules/evidence-connector-clickhouse/package.json`

but evidence is looking in 

`./node_modules/evidence-connector-clickhouse/src/package.json`

which causes

```
[ ! ] ENOENT: no such file or directory, open '/Users/amit/git/auto-report-gen/node_modules/evidence-connector-clickhouse/src/package.json'
```

### Steps to Reproduce

Create new Evidence project
Start it using VScode

1. `npm i evidence-connector-clickhouse`
2. add to `evidence.plugins.yaml`: `"evidence-connector-clickhouse": { }`
3. Add a Clickhouse connector via localhost:3000/settings (valid credentials are not required)
4. kill dev server
5. npm run sources

### Logs

```bash
> my-evidence-project@0.0.1 sources
> evidence sources

⠋ Loading plugins & sources(node:48586) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
✖ Loading plugins & sources
[ ! ] ENOENT: no such file or directory, open '/Users/amit/git/auto-report-gen/node_modules/evidence-connector-clickhouse/src/package.json'
```

### System Info

```Shell
~/Projects/repro-plugins$ npx envinfo --system --binaries --browsers --npmPackages

  System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 998.80 MB / 16.00 GB
    Shell: 5.1.16 - /opt/homebrew/bin/bash
  Binaries:
    Node: 22.11.0 - ~/.nvm/versions/node/v22.11.0/bin/node
    npm: 10.9.0 - ~/.nvm/versions/node/v22.11.0/bin/npm
    pnpm: 8.6.9 - /opt/homebrew/bin/pnpm
    bun: 1.0.25 - /opt/homebrew/bin/bun
  Browsers:
    Brave Browser: 123.1.64.122
    Chrome: 131.0.6778.71
    Safari: 17.2.1
  npmPackages:
    @evidence-dev/bigquery: ^2.0.8 => 2.0.8 
    @evidence-dev/core-components: ^4.8.13 => 4.8.13 
    @evidence-dev/csv: ^1.0.13 => 1.0.13 
    @evidence-dev/databricks: ^1.0.7 => 1.0.7 
    @evidence-dev/duckdb: ^1.0.12 => 1.0.12 
    @evidence-dev/evidence: ^39.1.17 => 39.1.17 
    @evidence-dev/motherduck: ^1.0.3 => 1.0.3 
    @evidence-dev/mssql: ^1.1.1 => 1.1.1 
    @evidence-dev/mysql: ^1.1.3 => 1.1.3 
    @evidence-dev/postgres: ^1.0.6 => 1.0.6 
    @evidence-dev/snowflake: ^1.2.1 => 1.2.1 
    @evidence-dev/sqlite: ^2.0.6 => 2.0.6 
    @evidence-dev/trino: ^1.0.8 => 1.0.8 
    evidence-connector-clickhouse: ^0.0.2 => 0.0.2
```

### Severity

blocking all usage of Evidence

### Additional Information, or Workarounds

create a new directory inside `node_modules/evidence-connector-clickhouse/src` and copied all the files.

**Comment by csjh** [comment] 2024-11-22 20:03
Unable to reproduce, seemed to be fixed in Archie's repro by deleting `.evidence`/`node_modules`/`package-lock.json` and re-installing

**Closed by csjh** 2024-11-22 20:03 UTC
Labels: bug, high-priority

**Comment by amit-cashify** [comment] 2024-11-23 02:15
> Unable to reproduce, seemed to be fixed in Archie's repro by deleting `.evidence`/`node_modules`/`package-lock.json` and re-installing

I had tried this as well, did not fix the issue for me.

**Comment by csjh** [comment] 2024-11-23 02:17
Are you able to reproduce step-by-step in a fresh template project?
