### ISSUE TITLE
Input nulls cause queries to not execute

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#1480] opened 2024-01-10 20:04 UTC
## Steps To Reproduce

Navigate to https://mdsinabox.com/nba/teams/

view the query `filtered_summary_by_team`

Inspect the SQL

![CleanShot 2024-01-10 at 15 00 45@2x](https://github.com/evidence-dev/evidence/assets/58074498/78533c19-d061-426c-b4a8-f8fbf381271a)

## Expected Behavior

The user has not selected a button yet, so the input result is null, and returns the expected query results for if `'${inputs.my_input}'` was null

## Actual Behaviour

![CleanShot 2024-01-10 at 15 00 45@2x](https://github.com/evidence-dev/evidence/assets/58074498/78533c19-d061-426c-b4a8-f8fbf381271a)

The query does not return data and so remains in a loading state

## Workarounds

Create an {#if} block before the results are available, returning different data. See [the source code](https://github.com/matsonj/nba-monte-carlo/blob/master/evidence/pages/nba/teams/index.md?plain=1)

**Comment by ItsMeBrianD** [comment] 2024-01-10 21:09
Duplicate of #1479

**Comment by archiewood** [comment] 2024-01-10 22:40
oops missed your issue

**Closed** 2024-01-10 22:40 UTC
Labels: bug, to-review
